
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkvsbejtpgbxqioiicxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrdnNiZWp0cGdieHFpb2lpY3hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MjU4MjgsImV4cCI6MjA1NzIwMTgyOH0.cuSmQ9rGSZXOggxTLSTbKc5Qq_EpjcIsN_sXe39K-R0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Configure with reasonable timeout and header options for performance
const supabaseOptions = {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: { 
      'x-application-name': 'water-mgmt-dashboard',
    },
    fetch: (url: RequestInfo, init?: RequestInit) => {
      // Add a timeout to prevent hanging requests
      // Use a longer timeout for file uploads (60 seconds instead of 30)
      const timeout = 60000;
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), timeout);
      
      return fetch(url, {
        ...init,
        signal: controller.signal,
      }).finally(() => clearTimeout(timeoutId));
    }
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, supabaseOptions);
